rosia:
  properties:
    ssh_name: rosia.pub-ops.kosendj-bu.in
    ssh_options:
      host_name: rosia.pub-ops.kosendj-bu.in
      user: dj
    run_list:
      - hosts/cnh/rosia/default.rb

akeno:
  properties:
    ssh_name: akeno.pub.kosendj-bu.in
    ssh_options:
      host_name: akeno.pub.kosendj-bu.in
      user: dj
    attributes:
      mysqld:
        server_id: "3"
    run_list:
      - hosts/akeno.rb
      - cookbooks/base/default.rb
      - cookbooks/iptables-persistent/auto.rb
      - roles/site-gateway/default.rb
      - cookbooks/nginx/default.rb
      - cookbooks/acmesmith-fetcher/default.rb
      - roles/nginx-backed-h2o/default.rb
      - cookbooks/mysql-client/default.rb
      - cookbooks/redis-client/default.rb
      - roles/mysql-server/default.rb
      - roles/redis-server/default.rb
      - roles/internal-dns/default.rb
      - roles/dns-cache/default.rb
      - roles/nginx-omniauth-adapter/default.rb
      - roles/gjcase/default.rb
      - roles/gj/default.rb
      - roles/camo/default.rb
      - roles/gjcase_storage_s3/default.rb

moeka:
  properties:
    ssh_name: moeka.box.c.kosendj-bu.in
    ssh_options:
      host_name: moeka.box.c.kosendj-bu.in
      user: dj
    attributes:
      platform: :baremetal
      mysqld:
        server_id: "4"
    run_list:
      - hosts/moeka.rb
      - cookbooks/base/default.rb
      - cookbooks/iptables-persistent/auto.rb
      - roles/site-gateway/default.rb
      - cookbooks/nginx/default.rb
      - cookbooks/acmesmith-fetcher/default.rb
      - roles/nginx-backed-h2o/default.rb
      - cookbooks/mysql-client/default.rb
      - cookbooks/redis-client/default.rb
      - roles/mysql-server/default.rb
      - roles/redis-server/default.rb
      - roles/box-router/default.rb
      - roles/camo/default.rb
      - roles/gjcase_storage/default.rb
      - roles/gjcase/default.rb
      - roles/gj/default.rb
